### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by freekmurze** [laravel-notification-channels/gcm#1]
Let me know when you're done with the initial code / tests / readme. I'll do a code review and set up packages, and other services

**Comment by barryvdh** [comment]
I have pushed the initial code with the new namespace with a very basic test for the message.
Changed the code to follow the the other channels (service provider, config location, dependency injection).

Please review and setup travis/packagist if you're happy for now :)

I'll ask a developer to test this on a working service tomorrow.

**Comment by freekmurze** [comment]
Cool, thanks for you work on this.

I did a review and only changed some minor things. I removed `.idea` from `.gitignore` as it's best practice to add that to a global `.gitignore`.

The package is now registered on packagist and all external services (travis, styleci, ...) have been started.

**Comment by barryvdh** [comment]
Ok thanks! I've updated the readme for some installation/usage examples.

It's not listed on the website though, should I add a PR there myself?

Could you also add me as maintainer on https://packagist.org/packages/laravel-notification-channels/gcm  ?

**Comment by themsaid** [comment]
@barryvdh now it's added to the website http://laravel-notification-channels.com/gcm/

I also added you as a maintainer on packagist :)
