### ISSUE TITLE
Getting error from GCM

### ISSUE THREAD

**Issue by zoranlorkovic** [laravel-notification-channels/gcm#10]
Hi,

Is it possible to get error in GCM directly in notification variable?

Something like $result = $user->notify(new GCMMessage($data));

So I can catch potential errors in $result.

Now it's always null no matter did GCM went through or not.

**Comment by antriver** [comment]
I'm not aware of a way to get the response synchronously in the location you send the notification. But you can listen for the NotificationFailed event to know when sending has failed:

```
        Event::listen(
            'Illuminate\Notifications\Events\NotificationFailed',
            function (NotificationFailed $event) {
                echo 'NotificationFailed';
                print_r($event->data);
            }
        );
```

**Comment by zoranlorkovic** [comment]
@antriver Oh, yeah. Will try that approach. Thank you for the tip.

**Comment by zoranlorkovic** [comment]
There is bug with handleFailedNotifications function in Gcmchannel.php file.

When firing event like this
```
            $this->events->fire(
                new NotificationFailed($notifiable, $notification, $this, [
                    'token' => $token,
                    'error' => $result['error'],
                ])
            );
```

laravel throws exception that Closure cannot be serialised.
It's because $this as argument as I believe this notification event should receive string as channel name.

Fix for this could be:

```
            $this->events->fire(
                new NotificationFailed($notifiable, $notification, get_class($this), [
                    'token' => $token,
                    'error' => $result['error'],
                ])
            );
```

**Comment by zoranlorkovic** [comment]
This is done now. Thank you for merge.
