### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by sagargulati** [laravel-notification-channels/gcm#12]
When can we expect the update for Laravel 5.4?

**Comment by barryvdh** [comment]
Sure, don't think much changed? Can you submit a PR?

**Comment by sagargulati** [comment]
Seems to work :)

**Comment by barryvdh** [comment]
? You need to pr the composer.json still

**Comment by sagargulati** [comment]
what is PR the composer.json meaning?

**Comment by barryvdh** [comment]
PR is pull request. The composer.json file is not yet updated, so you still can't install,  right?

**Comment by sagargulati** [comment]
I was able to install it with `"composer require laravel-notification-channels/gcm"` on Laravel 5.4

**Comment by zoranlorkovic** [comment]
I believe there should be change in handleFailedNotifications() method.

According to Laravel docs
"If you are manually implementing the Illuminate\Contracts\Events\Dispatcher interface in your application or package, you should rename the fire method to dispatch."

So,             
```
$this->events->fire(
                new NotificationFailed($notifiable, $notification, $this, [
                    'token' => $token,
                    'error' => $result['error'],
                ])
            );
```
should be
```
            $this->events->dispatch(
                new NotificationFailed($notifiable, $notification, $this, [
                    'token' => $token,
                    'error' => $result['error'],
                ])
            );
```

**Comment by sagargulati** [comment]
Changes noted :)
