### ISSUE TITLE
Update to zendservice-google-gcm ~2.0

### ISSUE THREAD

**Issue by aaronhuisinga** [laravel-notification-channels/gcm#16]
Zend updated their GCM library with support for FCM a few months ago. 
The release notes are here: https://github.com/zendframework/ZendService_Google_Gcm/releases/tag/release-2.0.0

FCM adds more features to push notifications, and Google are strongly advising all users on GCM to upgrade to FCM. Details on the differences from GCM to FCM are here: https://developers.google.com/cloud-messaging/faq

Migrating to this newer version and adding support for notification priorities would fix #6

**Comment by barryvdh** [comment]
Is the breaking BC? If not, can you make a Pr?

**Comment by dwightwatson** [comment]
Closing as the related PR was merged.
