### ISSUE TITLE
Send Notification is not optional

### ISSUE THREAD

**Issue by mmehdibalouchi** [laravel-notification-channels/gcm#23]
```
$packet->setNotification([
                'title' => $message->title,
                'body' => $message->message,
                'sound' => $message->sound,
            ] + $message->data);
```
this part of code should be option (just like apn content-available)

**Comment by dwightwatson** [comment]
Which part in part in particular should be optional?

Would you be able to put together a PR that implements the change you're after?

**Comment by atymic** [comment]
Closing as the package is deprecated
