### ISSUE TITLE
Gcm Deprecation

### ISSUE THREAD

**Issue by koenhoeijmakers** [laravel-notification-channels/gcm#30]
As of today google has announced to deprecate gcm and discontinue the service on the 11th of April in 2019, might be best to put up a deprecation notice in the package also?

**Comment by dwightwatson** [comment]
Happy to accept a PR for this.

**Comment by koenhoeijmakers** [comment]
Putting it in the readme would be one thing, but it might be a good idea to also deprecate the package later on on packagist, so that current installs get a notice that the package will be discontinued right?

**Comment by dwightwatson** [comment]
Ah, I see what you mean. Would have to ping one of the other maintainers to sort that out - I don't have access to the Packagist account for LNC. Not sure it's critical as the deadline is a year from now and anyone using GCM should be familiar with this.

**Comment by koenhoeijmakers** [comment]
correct, might be best to start notifying users when the fcm package is either moved to the LNC account or is known to stay on coreproc, so we can link it as a replacement

**Comment by kennyhorna** [comment]
It has been more than a year and yet there is no warning in the README 😞

**Comment by dwightwatson** [comment]
I've just added the deprecation notice to the top of the README. I assume anyone who is working with Android notifications would be aware of the GCM deprecation.
