### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/gcm#34]

**Comment by dwightwatson** [comment]
As this package has been deprecated (see #30) we won't implement 6.0 support. 

You might consider forking it to add support if you need it for your own projects.

Sorry this isn't the answer you're after.

**Comment by atymic** [comment]
My bad, missed that in the readme :)
I've created a PR to mark the package as deprecated on the site
https://github.com/laravel-notification-channels/laravel-notification-channels.github.io/pull/22
