### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/gcm#37]
Laravel 8 has been released today and we need to update this repo to support it.
See https://laravel.com/docs/8.x/upgrade & https://github.com/laravel-notification-channels/channels/issues/107

**Comment by dwightwatson** [comment]
As this channel as been deprecated, I'd suggest we not bother with this.

Perhaps it might make sense to archive the repo?

**Comment by atymic** [comment]
Yep, I auto created the issues with a script. Will archive now.
