### ISSUE TITLE
setApiKey not sending string or empty

### ISSUE THREAD

**Issue by zoranlorkovic** [laravel-notification-channels/gcm#7]
For some reason in GCM Service Provider, when setpApiKey function is called, it doesn't transfer string.

I've setup string in env file, and array in broadcasting file.

Also, I've try to dump it in home controller, and it worked fine. 
$gcmConfig = config('broadcasting.connections.gcm');
dd($gcmConfig['key']);

But in that function, it doesn't pass as I'm getting this exception.

exception 'ZendService\Google\Exception\InvalidArgumentException' with message 'The api key must be a string and not empty' in /home/vendor/zendframework/zendservice-google-gcm/library/ZendService/Google/Gcm/Client.php:64

**Comment by barryvdh** [comment]
How are you calling the channel? Could be a timing issue, if you try to instantiate it in the register phase.

**Comment by zoranlorkovic** [comment]
It's called in notification class with via method.

```
public function via($notifiable)
{
    return [GcmChannel::class];
}
```

**Comment by barryvdh** [comment]
And you did add the ServiceProvider to the config?

**Comment by barryvdh** [comment]
?

**Comment by zoranlorkovic** [comment]
Yep - in app.php
NotificationChannels\Gcm\GcmServiceProvider::class,

**Comment by zoranlorkovic** [comment]
It's working now so...will close it.
