### ISSUE TITLE
Using GCM to send notification to iOS

### ISSUE THREAD

**Issue by zoranlorkovic** [laravel-notification-channels/gcm#8]
Hi,

There is possibility to send push notifications to iOS devices through GCM.

But message that is send to GCM need to have specific structure which I couldn't accomplish with this package.

Is there plan maybe to add this option as well in this package? As it would be cool option to send both iOS and Android notifications through same package.

Kind regards.

**Comment by luisdalmolin** [comment]
I created a pull request for that: 

https://github.com/laravel-notification-channels/gcm/pull/9

**Comment by zoranlorkovic** [comment]
Cool. Thank you. Any special instruction for use in iOS or same as sending to Android according to current docs?

**Comment by zoranlorkovic** [comment]
It's working. Will close this one (dev branch).
